### PR TITLE
Tweak tsc config

### PR DESCRIPTION
**Pull request by cojj90**
For this PR, I wanted to turn on incremental build but after much fiddling, decided not to add it in because adding it breaks `npm t` command.

Also, I wanted to add `strict` flag but concluded not to turn it on at the time being because there is so many type definition issues we need to fix especially in `@mishguru/data` package.

I've added these flags(ref: https://www.typescriptlang.org/docs/handbook/compiler-options.html):

diagnostics
forceConsistentCasingInFileNames
noUnusedLocals
noUnusedParameters
removeComments

Most of these is being checked by our linter but why not check at compiler level :D?

### CODE REVIEW

**Comment by stayradiated** [comment]
Nice one CJ! Thank you for looking into this!

> For this PR, I wanted to turn on incremental build but after much fiddling, decided not to add it in because adding it breaks npm t command.

I don't know much about incremental builds, but it sounds like this _should_ be possible to configure - what sort of issues did you run into?

> Also, I wanted to add strict flag but concluded not to turn it on at the time being because there is so many type definition issues we need to fix especially in @mishguru/data package.

What does strict mode do?

**Comment by stayradiated** [comment]
Oh, found it in the doc you linked.

```
Enable all strict type checking options.
Enabling --strict enables --noImplicitAny, --noImplicitThis, --alwaysStrict, --strictBindCallApply, --strictNullChecks, --strictFunctionTypes and --strictPropertyInitialization
```

I imagine that `--strictNullChecks` causes us a lot of headaches.

**Comment by brendonjohn** [comment]
> I imagine that --strictNullChecks causes us a lot of headaches.

I want to see this compiler feature adopted. It's a reasonable and well accepted standard to meet.

What headaches do you have in mind @stayradiated? I'm happy for this to go ahead as I think it will put the right kind of pressure to improve our implementations.

**Comment by cojj90** [comment]
> I don't know much about incremental builds, but it sounds like this should be possible to configure - what sort of issues did you run into?

When we delete the dist folder, we also need to delete the 'tsbuildinfo' file that gets generated when we do a incremental build or else, the next time we build, dist folder will look very empty.

**Pull request merged**
